### ISSUE TITLE
Mac M1 compatibility?

### ISSUE THREAD

**Issue by fuad00** [ipwnosx/Hopper-4.5.24-Linux#1]
Ubuntu ARM64 is not supported. Any way to run a crack on Mac M1?

**Comment by zer0mania** [comment]
Try running with it UTM https://getutm.app/

**Comment by ipwnosx** [comment]
Yea iv never used. So idk

**Comment by antgame11** [comment]
> Ubuntu ARM64 is not supported. Any way to run a crack on Mac M1?

try box86/box64
